"""
mappings.py — Lookup tables for Tolkienizer

Covers:
  - PERSON_POOL: ordered list of Tolkien characters for hash-based fallback
  - PERSON_MAPPINGS: common first names → specific Tolkien characters
  - LOCATION_POOL: ordered list of Middle-earth locations for hash-based fallback
  - LOCATION_MAPPINGS: real-world cities/countries → Middle-earth locations
  - ARCHAIC_SUBSTITUTIONS: modern phrases → Tolkien-register equivalents
  - THEMATIC_SUBSTITUTIONS: semantic swaps (friend→companion, enemy→foe, etc.)
"""

# ──────────────────────────────────────────────
# Character pool (used for deterministic fallback)
# Drawn from LotR, The Silmarillion, The Children of Húrin,
# Unfinished Tales, and The Hobbit.
# ──────────────────────────────────────────────
PERSON_POOL = [
    # ── The Lord of the Rings ──────────────────
    "Aragorn", "Legolas", "Gimli", "Gandalf", "Frodo", "Samwise",
    "Peregrin", "Meriadoc", "Boromir", "Faramir", "Éowyn", "Galadriel",
    "Elrond", "Arwen", "Théoden", "Bilbo", "Glorfindel", "Celeborn",
    "Haldir", "Éomer", "Treebeard", "Shadowfax", "Círdan", "Denethor",
    "Beregond", "Bergil", "Ioreth", "Goldberry", "Tom Bombadil",
    "Radagast", "Pallando", "Alatar", "Celebrimbor", "Gil-galad",
    "Isildur", "Anárion", "Elendil", "Glóin", "Balin", "Dwalin",
    "Bombur", "Bofur", "Bifur", "Dori", "Nori", "Ori", "Óin",
    # ── The Hobbit ────────────────────────────
    "Thorin Oakenshield", "Fíli", "Kíli", "Bard the Bowman",
    "Thranduil", "Beorn", "Smaug", "Bard", "Dáin Ironfoot",
    # ── The Silmarillion — Noldor ─────────────
    "Fëanor", "Nerdanel", "Maedhros", "Maglor", "Celegorm",
    "Caranthir", "Curufin", "Amrod", "Amras", "Fingolfin",
    "Fingon", "Turgon", "Aredhel", "Idril", "Finrod Felagund",
    "Orodreth", "Angrod", "Aegnor", "Celebrimbor",
    # ── The Silmarillion — Sindar & Doriath ───
    "Thingol", "Melian", "Lúthien Tinúviel", "Dior", "Nimloth",
    "Beleg Cúthalion", "Mablung", "Daeron",
    # ── The Silmarillion — Men ────────────────
    "Beren", "Húrin", "Morwen", "Túrin Turambar", "Niënor",
    "Tuor", "Rían", "Eärendil", "Elwing", "Haleth",
    "Bëor", "Hador", "Andreth", "Adanel",
    # ── The Silmarillion — Valar & Maiar ──────
    "Manwë", "Varda", "Ulmo", "Aulë", "Yavanna", "Mandos",
    "Oromë", "Estë", "Vairë", "Tulkas", "Nessa", "Nienna",
    "Eönwë", "Ilmarë", "Ossë", "Uinen", "Melian",
    # ── The Silmarillion — Antagonists ────────
    "Morgoth", "Sauron", "Gothmog", "Glaurung", "Ancalagon",
    "Ungoliant", "Draugluin", "Thuringwethil",
    # ── Númenor (Silmarillion / UT) ───────────
    "Tar-Míriel", "Ar-Pharazôn", "Amandil", "Elendil", "Anárion",
    "Tar-Palantir", "Tar-Aldarion", "Tar-Ancalimë", "Silmariën",
    # ── Unfinished Tales ──────────────────────
    "Turambar", "Nienor", "Brandir", "Dorlas", "Sador",
    "Azaghâl", "Khîm", "Mîm",
]

# ──────────────────────────────────────────────
# Named person mappings  (lowercase key → Tolkien name)
# ──────────────────────────────────────────────
PERSON_MAPPINGS: dict[str, str] = {
    # Common English male names
    "james": "Boromir",
    "john": "Aragorn",
    "robert": "Faramir",
    "michael": "Glorfindel",
    "william": "Elendil",
    "david": "Elrond",
    "richard": "Isildur",
    "joseph": "Théodred",
    "thomas": "Théoden",
    "charles": "Denethor",
    "christopher": "Círdan",
    "daniel": "Éomer",
    "matthew": "Haldir",
    "anthony": "Celeborn",
    "mark": "Beregond",
    "donald": "Treebeard",
    "steven": "Radagast",
    "paul": "Pallando",
    "andrew": "Celebrimbor",
    "joshua": "Gil-galad",
    "kenneth": "Balin",
    "kevin": "Dwalin",
    "brian": "Glóin",
    "george": "Thorin",
    "edward": "Bifur",
    "ronald": "Bofur",
    "timothy": "Bombur",
    "jason": "Kíli",
    "jeffrey": "Fíli",
    "ryan": "Ori",
    "jacob": "Nori",
    "gary": "Dori",
    "nicholas": "Óin",
    "eric": "Legolas",
    "jonathan": "Gimli",
    "stephen": "Peregrin",
    "larry": "Meriadoc",
    "justin": "Samwise",
    "scott": "Frodo",
    "brandon": "Bilbo",
    "benjamin": "Tom Bombadil",
    "samuel": "Samwise",
    "frank": "Gandalf",
    "alexander": "Saruman",
    "raymond": "Sauron's herald",
    "gregory": "Gothmog",
    "frank": "Gandalf",
    "patrick": "Pippin",
    "jack": "Frodo",
    "henry": "Helm Hammerhand",
    "arthur": "Ar-Pharazôn",
    "peter": "Peregrin",
    "alan": "Alatar",
    "adam": "Ádanel",
    "carl": "Círdan",
    "harry": "Halbarad",
    "sean": "Shagrat",
    "aaron": "Anarion",
    "phillip": "Pallando",
    "fred": "Fredegar Bolger",
    "albert": "Aldor",
    "joe": "Jolly Cotton",
    "tom": "Tom Bombadil",
    "sam": "Samwise",
    "jim": "Gimli",
    "bob": "Bombur",
    "bill": "Bill the Pony",
    "ben": "Beren",
    "max": "Mablung",
    "alex": "Alatar",
    "chris": "Círdan",
    "matt": "Mablung",
    "mike": "Merry",
    "dave": "Dwalin",
    "steve": "Shadowfax",
    "brad": "Barad",
    "dan": "Denethor",
    "tim": "Treebeard",
    "tony": "Túrin",
    "rick": "Radagast",
    "nick": "Nori",
    "ray": "Radagast",
    "ken": "Khamûl",
    "ted": "Théodred",
    "ed": "Éomer",
    "phil": "Pallando",
    "greg": "Grimbeorn",
    "larry": "Legolas",
    "gary": "Gimli",
    "barry": "Barliman Butterbur",
    "terry": "Treebeard",
    # Common English female names
    "mary": "Galadriel",
    "patricia": "Arwen",
    "jennifer": "Éowyn",
    "linda": "Lúthien",
    "barbara": "Berúthiel",
    "elizabeth": "Elwing",
    "susan": "Silmariën",
    "jessica": "Gilraen",
    "sarah": "Shieldmaiden of Rohan",
    "karen": "Kementári",
    "lisa": "Lúthien",
    "nancy": "Nerdanel",
    "betty": "Berúthiel",
    "helen": "Haleth",
    "donna": "Dirhael's wife",
    "carol": "Celebrían",
    "ruth": "Rían",
    "sharon": "Silmariën",
    "michelle": "Míriel",
    "laura": "Lúthien",
    "sarah": "Gilraen",
    "kimberly": "Kementári",
    "deborah": "Dirhael's kin",
    "jessica": "Gilraen",
    "shirley": "Shelob",
    "angela": "Arwen",
    "melissa": "Míriel",
    "brenda": "Berúthiel",
    "amy": "Arwen",
    "anna": "Andreth",
    "emma": "Elwing",
    "emily": "Eldalótë",
    "kate": "Kementári",
    "alice": "Arwen",
    "grace": "Galadriel",
    "rose": "Rosie Cotton",
    "lily": "Lúthien",
    "victoria": "Varda",
    "diana": "Dís",
    "claire": "Celebrían",
    "sophie": "Silmariën",
    "charlotte": "Celebrían",
    "olivia": "Olwë's daughter",
    "isabella": "Idril",
    "mia": "Míriel",
    "eve": "Elwing",
    "nina": "Niënor",
    "vera": "Varda",
    "cathy": "Celebrían",
    "helen": "Haleth",
    "joan": "Gilraen",
    "jean": "Gilraen",
    "ann": "Andreth",
    "sue": "Silmariën",
    "kim": "Kementári",
    "julia": "Gilraen",
    "rachel": "Rían",
    "rebecca": "Rían",
    "diana": "Dís",
    "tracy": "Tar-Míriel",
}

# ──────────────────────────────────────────────
# Location pool (used for deterministic fallback)
# Drawn from LotR, The Silmarillion, UT, and The Hobbit.
# ──────────────────────────────────────────────
LOCATION_POOL = [
    # ── LotR / Third Age ──────────────────────
    "Minas Tirith", "Rivendell", "Lothlórien", "The Shire", "Rohan",
    "Gondor", "Mordor", "Isengard", "Helm's Deep", "Edoras",
    "Mirkwood", "Erebor", "Dale", "Bree", "Weathertop",
    "Khazad-dûm", "Osgiliath", "Ithilien", "Pelargir",
    "Minas Morgul", "Cirith Ungol", "Mount Doom", "Barad-dûr",
    "The Grey Havens", "Fangorn", "Emyn Muil", "Amon Hen",
    "Dunharrow", "Paths of the Dead", "Pelennor Fields",
    "Cair Andros", "Umbar", "Rhûn", "Forodwaith",
    "The Iron Hills", "The Blue Mountains", "Fornost", "Annúminas",
    "Weathertop", "The Prancing Pony", "Buckland", "Tuckborough",
    "Bag End", "Hobbiton", "Bywater", "Michel Delving",
    "Minhiriath", "Enedwaith", "Dunland", "The Wold",
    "Amon Dîn", "Nardol", "Eilenach", "Erelas", "Min-Rimmon",
    "Calenhad", "Halifirien",
    # ── Númenor / Second Age ──────────────────
    "Númenor", "Armenelos", "Andúnië", "Rómenna", "The Meneltarma",
    "Tar-Minastir's citadel",
    # ── Valinor / Aman ────────────────────────
    "Valinor", "Aman", "Tol Eressëa", "Tirion upon Túna",
    "Formenos", "Alqualondë", "Valmar", "Taniquetil",
    "The Two Trees", "The Halls of Mandos", "Gardens of Lórien",
    # ── Beleriand / First Age ─────────────────
    "Beleriand", "Nargothrond", "Doriath", "Gondolin", "Menegroth",
    "Angband", "Utumno", "Thangorodrim", "Hithlum", "Dorthonion",
    "Lothlann", "Ossiriand", "Thargelion", "Nevrast", "Vinyamar",
    "Nan Elmoth", "Brethil", "The Forest of Brethil",
    "The Mouths of Sirion", "Arvernien", "Isle of Balar",
    "Ered Wethrin", "Ard-galen", "Anfauglith",
    "The Pass of Aglon", "Himring", "Tol Sirion",
]

# ──────────────────────────────────────────────
# Named location mappings  (lowercase key → Middle-earth location)
# ──────────────────────────────────────────────
LOCATION_MAPPINGS: dict[str, str] = {
    # ── Major world cities ────────────────────
    "new york": "Minas Tirith",
    "new york city": "Minas Tirith",
    "nyc": "Minas Tirith",
    "london": "Minas Morgul",
    "paris": "Rivendell",
    "tokyo": "Lothlórien",
    "beijing": "Barad-dûr",
    "moscow": "Angband",
    "berlin": "Edoras",
    "rome": "Osgiliath",
    "madrid": "Pelargir",
    "amsterdam": "The Grey Havens",
    "brussels": "Tirion upon Túna",
    "vienna": "Gondolin",
    "athens": "Nargothrond",
    "istanbul": "Umbar",
    "dubai": "Armenelos",
    "singapore": "Tol Eressëa",
    "sydney": "Bag End",
    "melbourne": "Hobbiton",
    "toronto": "Fornost",
    "chicago": "Helm's Deep",
    "los angeles": "Isengard",
    "san francisco": "Valinor",
    "seattle": "Alqualondë",
    "boston": "Annúminas",
    "washington": "The White Tower of Ecthelion",
    "houston": "Dunharrow",
    "dallas": "Edoras",
    "miami": "Pelargir",
    "atlanta": "Dale",
    "denver": "Weathertop",
    "phoenix": "Anfauglith",
    "las vegas": "Umbar",
    "portland": "Bree",
    "austin": "The Prancing Pony",
    "nashville": "Harrowdale",
    "minneapolis": "Erebor",
    "detroit": "Khazad-dûm",
    "philadelphia": "Osgiliath",
    "barcelona": "Pelargir",
    "milan": "Armenelos",
    "munich": "The Lonely Mountain",
    "stockholm": "Himring",
    "oslo": "Forodwaith",
    "copenhagen": "The Ice Bay of Forochel",
    "zurich": "Rivendell",
    "prague": "Dorthonion",
    "warsaw": "Ered Wethrin",
    "kyiv": "Beleriand",
    "cairo": "Anfauglith",
    "mumbai": "Harad",
    "shanghai": "Rhûn",
    "seoul": "Lothlórien",
    "hong kong": "Pelargir",
    "bangkok": "Ossiriand",
    "jakarta": "Thargelion",
    "buenos aires": "Númenor",
    "são paulo": "Arvernien",
    "mexico city": "Umbar",
    "johannesburg": "Brown Lands",
    "nairobi": "Harad",
    # ── Countries ────────────────────────────
    "united states": "Gondor",
    "usa": "Gondor",
    "america": "Gondor",
    "united kingdom": "The Shire",
    "uk": "The Shire",
    "england": "Rohan",
    "scotland": "The Iron Hills",
    "ireland": "The Green Hills of the Shire",
    "wales": "Dunland",
    "france": "Rivendell",
    "germany": "Rohan",
    "russia": "Mordor",
    "china": "Rhûn",
    "japan": "Lothlórien",
    "italy": "Osgiliath",
    "spain": "Pelargir",
    "canada": "Eriador",
    "australia": "The Shire",
    "india": "Harad",
    "brazil": "Númenor",
    "mexico": "Umbar",
    "south korea": "Mirkwood",
    "netherlands": "The Grey Havens",
    "sweden": "Forodwaith",
    "norway": "The Ice Bay of Forochel",
    "denmark": "The Blue Mountains",
    "finland": "Himring",
    "switzerland": "Rivendell",
    "austria": "Gondolin",
    "poland": "Ered Wethrin",
    "ukraine": "Beleriand",
    "turkey": "Umbar",
    "israel": "Nargothrond",
    "iran": "Mordor",
    "iraq": "Angband",
    "saudi arabia": "Harad",
    "egypt": "Anfauglith",
    "south africa": "Brown Lands",
    "nigeria": "Thargelion",
    "kenya": "Ossiriand",
    "argentina": "Arvernien",
    "chile": "Ered Luin",
    "colombia": "Ossiriand",
    "venezuela": "Tol Sirion",
    "peru": "The Iron Hills",
    "new zealand": "Tol Eressëa",
    "indonesia": "Isle of Balar",
    "philippines": "Nevrast",
    "vietnam": "Nan Elmoth",
    "thailand": "Brethil",
    "pakistan": "Dorthonion",
    "bangladesh": "Hithlum",
    "ethiopia": "Harad",
    "ghana": "Ossiriand",
    "tanzania": "Ossiriand",
    # ── US States ─────────────────────────────
    "california": "Valinor",
    "texas": "Rohan",
    "new york state": "Gondor",
    "florida": "Pelargir",
    "illinois": "Isengard",
    "washington state": "Alqualondë",
    "colorado": "The Misty Mountains",
    "oregon": "Fangorn",
    "nevada": "Anfauglith",
    "arizona": "Brown Lands",
    "massachusetts": "Annúminas",
    "virginia": "Ithilien",
    "pennsylvania": "Osgiliath",
    "ohio": "Dunharrow",
    "michigan": "Khazad-dûm",
    "minnesota": "Erebor",
    "tennessee": "Harrowdale",
    "georgia": "Dale",
    "north carolina": "Ered Nimrais",
    "new jersey": "Cair Andros",
    "indiana": "Minhiriath",
    "missouri": "Enedwaith",
    "wisconsin": "Mirkwood",
    "maryland": "Ithilien",
    "arizona": "Brown Lands",
    "utah": "The Misty Mountains",
    "idaho": "Forodwaith",
    "montana": "Rhudaur",
    "wyoming": "The Wold",
    "alaska": "Helcaraxë",
    "hawaii": "Tol Eressëa",
    # ── Geographical features ─────────────────
    "atlantic ocean": "Belegaer",
    "pacific ocean": "The Sundering Seas",
    "mediterranean sea": "The Sea of Rhûn",
    "north sea": "The Ice Bay of Forochel",
    "arctic": "Forodwaith",
    "antarctica": "Helcaraxë",
    "himalayas": "The Misty Mountains",
    "alps": "The White Mountains",
    "andes": "The Iron Hills",
    "rocky mountains": "Ered Luin",
    "amazon": "Fangorn",
    "mississippi": "Anduin",
    "nile": "The River Narog",
    "thames": "Brandywine",
    "seine": "Bruinen",
    "rhine": "Celebrant",
    "danube": "The River Sirion",
    "amazon river": "Great River Anduin",
    "mount everest": "Mount Doom",
    "sahara": "Brown Lands",
    "amazon rainforest": "Fangorn Forest",
    "great barrier reef": "The Sundering Seas",
    # ── Landmarks ────────────────────────────
    "wall street": "the markets of Dale",
    "the white house": "Meduseld",
    "the pentagon": "the Tower of Ecthelion",
    "buckingham palace": "the halls of Meduseld",
    "the eiffel tower": "the Tower of Orthanc",
    "the colosseum": "the Pelennor Fields",
    "the great wall": "the Rammas Echor",
    "the kremlin": "Barad-dûr",
    "the vatican": "the Halls of Mandos",
    "times square": "the Great Gate of Minas Tirith",
}

# ──────────────────────────────────────────────
# Archaic / register substitutions (regex-safe literal strings)
# Applied as whole-word case-insensitive replacements BEFORE LLM rewriting.
# Ordered from most-specific to least-specific to avoid partial-match issues.
# ──────────────────────────────────────────────
ARCHAIC_SUBSTITUTIONS: list[tuple[str, str]] = [
    # Contractions → full forms (must come first)
    ("can't", "cannot"),
    ("won't", "will not"),
    ("don't", "do not"),
    ("didn't", "did not"),
    ("doesn't", "does not"),
    ("wouldn't", "would not"),
    ("shouldn't", "should not"),
    ("couldn't", "could not"),
    ("haven't", "have not"),
    ("hasn't", "has not"),
    ("hadn't", "had not"),
    ("I'm", "I am"),
    ("you're", "you are"),
    ("we're", "we are"),
    ("they're", "they are"),
    ("it's", "it is"),
    ("that's", "that is"),
    ("there's", "there is"),
    ("here's", "here is"),
    ("I've", "I have"),
    ("you've", "you have"),
    ("we've", "we have"),
    ("they've", "they have"),
    ("I'd", "I would"),
    ("you'd", "you would"),
    ("he'd", "he would"),
    ("she'd", "she would"),
    ("we'd", "we would"),
    ("they'd", "they would"),
    ("I'll", "I shall"),
    ("you'll", "you shall"),
    ("he'll", "he shall"),
    ("she'll", "she shall"),
    ("we'll", "we shall"),
    ("they'll", "they shall"),
    # Modal upgrades
    ("will", "shall"),
    # Temporal
    ("before", "ere"),
    ("afterward", "thereafter"),
    ("soon", "ere long"),
    # Connectives
    ("because", "for"),
    ("although", "yet"),
    ("however", "yet"),
    # Intensifiers
    ("very", "most"),
    ("really", "truly"),
    ("extremely", "exceedingly"),
    ("quite", "rather"),
    ("totally", "utterly"),
    ("absolutely", "verily"),
    ("definitely", "indeed"),
    ("certainly", "assuredly"),
    ("obviously", "plainly"),
    ("basically", "in truth"),
    ("actually", "in sooth"),
    ("anyway", "be that as it may"),
    # Discourse markers
    ("okay", "very well"),
    ("ok", "very well"),
    ("yeah", "aye"),
    ("yes", "aye"),
    ("no", "nay"),
    ("hello", "hail"),
    ("hi", "hail"),
    ("hey", "hark"),
    ("bye", "farewell"),
    ("goodbye", "farewell"),
    ("thanks", "I thank thee"),
    ("thank you", "I give thee thanks"),
    ("please", "I prithee"),
    ("sorry", "I beg thy pardon"),
    # Thematic vocabulary
    ("friend", "companion"),
    ("friends", "companions"),
    ("enemy", "foe"),
    ("enemies", "foes"),
    ("bad", "dark"),
    ("evil", "shadow"),
    ("fight", "battle"),
    ("fighting", "warring"),
    ("war", "great war"),
    ("army", "host"),
    ("soldier", "warrior"),
    ("soldiers", "warriors"),
    ("king", "lord"),
    ("queen", "lady"),
    ("government", "council"),
    ("city", "citadel"),
    ("cities", "citadels"),
    ("town", "settlement"),
    ("house", "hall"),
    ("home", "dwelling"),
    ("road", "road"),  # keep — common in Tolkien
    ("journey", "quest"),
    ("trip", "journey"),
    ("travel", "wayfaring"),
    ("tired", "weary"),
    ("happy", "glad"),
    ("sad", "sorrowful"),
    ("angry", "wrathful"),
    ("scared", "afraid"),
    ("strong", "mighty"),
    ("weak", "feeble"),
    ("old", "ancient"),
    ("new", "newly-wrought"),
    ("big", "great"),
    ("small", "little"),
    ("fast", "swift"),
    ("slow", "tardy"),
    ("dark", "shadow-dark"),
    ("light", "radiant"),
    ("beautiful", "fair"),
    ("ugly", "misshapen"),
    ("smart", "wise"),
    ("stupid", "witless"),
    ("dead", "fallen"),
    ("die", "fall"),
    ("died", "fell"),
    ("dies", "falls"),
    ("kill", "slay"),
    ("killed", "slain"),
    ("kills", "slays"),
    ("start", "begin"),
    ("started", "began"),
    ("end", "conclude"),
    ("ended", "concluded"),
    ("help", "aid"),
    ("helped", "aided"),
    ("try", "endeavour"),
    ("tried", "endeavoured"),
    ("think", "deem"),
    ("thought", "deemed"),
    ("know", "know well"),
    ("people", "folk"),
    ("world", "realm"),
    ("sky", "heavens"),
    ("sun", "the Sun"),
    ("moon", "the Moon"),
    ("stars", "the stars of Varda"),
    ("magic", "enchantment"),
    ("power", "might"),
    ("ring", "Ring of Power"),
    ("rings", "Rings of Power"),
    ("technology", "craft"),
    ("computer", "palantír"),
    ("computers", "palantíri"),
    ("phone", "far-speaker"),
    ("internet", "the web of knowledge"),
    ("email", "missive"),
    ("message", "tidings"),
    ("news", "tidings"),
    ("meeting", "council"),
    ("office", "hall of works"),
    ("work", "labour"),
    ("job", "appointed task"),
    ("money", "coin"),
    ("gold", "gold"),  # already Tolkien
    ("company", "fellowship"),
    ("team", "fellowship"),
    ("group", "company"),
    ("plan", "counsel"),
    ("idea", "counsel"),
    ("problem", "shadow"),
    ("solution", "remedy"),
    ("challenge", "trial"),
    ("opportunity", "fortune"),
    ("decision", "counsel"),
    ("choice", "choosing"),
]

# ──────────────────────────────────────────────
# Organisation-type mappings
# ──────────────────────────────────────────────
ORG_POOL = [
    "the Fellowship", "the White Council", "the Council of Elrond",
    "the Rohirrim", "the Rangers of the North", "the Company of Thorin",
    "the Ents of Fangorn", "the Grey Company", "the Order of Wizards",
    "the Dunedain", "the Eldar", "the Noldor", "the Sindar",
    "the Dwarves of Erebor", "the Iron Guard", "the Citadel Guard",
    "the Tower Guard of Minas Tirith", "the Easterlings",
    "the Haradrim", "the Corsairs of Umbar", "the Nine Riders",
]
